---
k3s_version: v1.17.5+k3s1
ansible_user: pi
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""

# Uncomment (and modify if necessary) the following to set the time zone set for
# all members of the cluster.
timezone: US/Pacific

